### ISSUE TITLE
WebSocket connection to failed: Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by erick3000** [gnuns/omigo#10]
Hi, Mate

Al thought everything works i am getting this error in chrome console, 

https://i.imgur.com/5TeHG9M.png

Should i worry about it? anyway to fix that error?

Regards

**Comment by gnuns** [comment]
Hi! Adding the following lines on your nginx config should solve this:
```conf
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_set_header Host $host;
```

**Comment by erick3000** [comment]
Cool, one last thing, any way to make it work on mobile? chat works just
not camera

**Comment by gnuns** [comment]
What browser are you using? The video chat feature works fine on Chrome and Firefox Mobile (android). It can also be a permission issue or something like this.
