### ISSUE TITLE
Add SSL Cert to it?

### ISSUE THREAD

**Issue by erick3000** [gnuns/omigo#9]
Hi, 

What is the correct way to add a key and crt to listen with ssl?

**Comment by gnuns** [comment]
Hi, @erick3000! The recommended way is to run the server [behind a reverse proxy like nginx](https://www.sitepoint.com/configuring-nginx-ssl-node-js/). This way only the reverse proxy will deal with the SSL certs.

**Comment by erick3000** [comment]
Hi

Right but how do you add the ssl to it? I already have the key and cert

**Comment by gnuns** [comment]
Add this to your nginx configuration:
```sh
server {
  listen       80;
  listen       443 ssl;
  server_name  localhost;

  # ############### key and cert:
  ssl_certificate  /etc/nginx/ssl/server.crt
  ssl_certificate_key /etc/nginx/ssl/server.key

  location / {
    proxy_pass http://localhost:3000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }
}
```

**Comment by erick3000** [comment]
Got you, i was trying to some how add it in the app.js hehe. Thank you very much. The app doesn't work on chrome without ssl as it should not being encrypted it has no business
